[package]
name = "companion-for-processbot-local"
version = "0.1.0"
authors = ["mak-parity-org2 <info@parity.io>"]
edition = "2018"

[dependencies]
main-for-processbot-local = { git = "https://github.com/mak-parity-org2/main-for-processbot-local", branch = "master" }
